# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class sandbox-iden-catboost-risk-model:
        name: str
        type: str
        url: str

